; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Aug 07 2020 20:14:47 GMT+0100 (GMT Summer Time)
; ================================================================================

DATAUSX0OGXEZM8:
	dc.w DATAUSX0OGXEZM8_0-DATAUSX0OGXEZM8, DATAUSX0OGXEZM8_1-DATAUSX0OGXEZM8
	dc.w DATAUSX0OGXEZM8_2-DATAUSX0OGXEZM8, DATAUSX0OGXEZM8_3-DATAUSX0OGXEZM8
	dc.w DATAUSX0OGXEZM8_4-DATAUSX0OGXEZM8
DATAUSX0OGXEZM8_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
DATAUSX0OGXEZM8_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
DATAUSX0OGXEZM8_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
DATAUSX0OGXEZM8_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
DATAUSX0OGXEZM8_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even