; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Aug 16 2020 19:01:13 GMT+0100 (GMT Summer Time)
; ================================================================================

DATA96BQSPO3J5Q:
	dc.w DATA96BQSPO3J5Q_0-DATA96BQSPO3J5Q, DATA96BQSPO3J5Q_1-DATA96BQSPO3J5Q
	dc.w DATA96BQSPO3J5Q_2-DATA96BQSPO3J5Q, DATA96BQSPO3J5Q_3-DATA96BQSPO3J5Q
	dc.w DATA96BQSPO3J5Q_4-DATA96BQSPO3J5Q, DATA96BQSPO3J5Q_5-DATA96BQSPO3J5Q
	dc.w DATA96BQSPO3J5Q_6-DATA96BQSPO3J5Q
DATA96BQSPO3J5Q_0: dc.b $6
	dc.b $D8, $7, $0, $0, $F8
	dc.b $F8, $E, $0, $8, $D8
	dc.b $F8, $F, $0, $14, $F8
	dc.b $F8, $6, $0, $24, $18
	dc.b $10, $4, $0, $2A, $E8
	dc.b $18, $C, $0, $2C, $F0
DATA96BQSPO3J5Q_1: dc.b $6
	dc.b $D8, $7, $0, $0, $F8
	dc.b $F8, $E, $0, $8, $D8
	dc.b $F8, $F, $0, $14, $F8
	dc.b $F8, $6, $0, $24, $18
	dc.b $10, $4, $0, $2A, $E8
	dc.b $18, $C, $0, $2C, $F0
DATA96BQSPO3J5Q_2: dc.b $6
	dc.b $D8, $7, $0, $0, $F8
	dc.b $F8, $E, $0, $8, $D8
	dc.b $F8, $F, $0, $14, $F8
	dc.b $F8, $6, $0, $24, $18
	dc.b $10, $4, $0, $2A, $E8
	dc.b $18, $C, $0, $2C, $F0
DATA96BQSPO3J5Q_3: dc.b $6
	dc.b $D8, $7, $0, $0, $F8
	dc.b $F8, $E, $0, $8, $D8
	dc.b $F8, $F, $0, $14, $F8
	dc.b $F8, $6, $0, $24, $18
	dc.b $10, $4, $0, $2A, $E8
	dc.b $18, $C, $0, $2C, $F0
DATA96BQSPO3J5Q_4: dc.b $6
	dc.b $D8, $7, $0, $0, $F8
	dc.b $F8, $E, $0, $8, $D8
	dc.b $F8, $F, $0, $14, $F8
	dc.b $F8, $6, $0, $24, $18
	dc.b $10, $4, $0, $2A, $E8
	dc.b $18, $C, $0, $2C, $F0
DATA96BQSPO3J5Q_5: dc.b $1
	dc.b $F8, $5, $0, $30, $F8
DATA96BQSPO3J5Q_6: dc.b $1
	dc.b $F8, $5, $0, $34, $F8
	even