; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Nov 13 2020 16:59:42 GMT+0000 (GMT Standard Time)
; ================================================================================

DATAK01DVY8S8QR:
	dc.w DATAK01DVY8S8QR_0-DATAK01DVY8S8QR, DATAK01DVY8S8QR_1-DATAK01DVY8S8QR
	dc.w DATAK01DVY8S8QR_2-DATAK01DVY8S8QR, DATAK01DVY8S8QR_3-DATAK01DVY8S8QR
DATAK01DVY8S8QR_0: dc.b $4
	dc.b $EC, $F, $0, $0, $F0
	dc.b $FC, $0, $0, $10, $E8
	dc.b $4, $0, $0, $11, $10
	dc.b $C, $C, $0, $12, $F0
DATAK01DVY8S8QR_1: dc.b $4
	dc.b $EC, $F, $0, $0, $F0
	dc.b $FC, $0, $0, $10, $E8
	dc.b $4, $0, $0, $11, $10
	dc.b $C, $C, $0, $12, $F0
DATAK01DVY8S8QR_2: dc.b $4
	dc.b $EC, $F, $0, $0, $F0
	dc.b $FC, $0, $0, $10, $E8
	dc.b $4, $0, $0, $11, $10
	dc.b $C, $C, $0, $12, $F0
DATAK01DVY8S8QR_3: dc.b $4
	dc.b $EC, $F, $0, $0, $F0
	dc.b $FC, $0, $0, $10, $E8
	dc.b $4, $0, $0, $11, $10
	dc.b $C, $C, $0, $12, $F0
	even