; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Nov 10 2020 21:23:45 GMT+0000 (GMT Standard Time)
; ================================================================================

DATABKLPPLZRGGB:
	dc.w DATABKLPPLZRGGB_0-DATABKLPPLZRGGB, DATABKLPPLZRGGB_1-DATABKLPPLZRGGB
	dc.w DATABKLPPLZRGGB_2-DATABKLPPLZRGGB, DATABKLPPLZRGGB_3-DATABKLPPLZRGGB
	dc.w DATABKLPPLZRGGB_4-DATABKLPPLZRGGB, DATABKLPPLZRGGB_5-DATABKLPPLZRGGB
	dc.w DATABKLPPLZRGGB_6-DATABKLPPLZRGGB
DATABKLPPLZRGGB_0: dc.b $2
	dc.b $F1, $B, $8, $0, $F6
	dc.b $11, $8, $8, $C, $F6
DATABKLPPLZRGGB_1: dc.b $2
	dc.b $F1, $B, $8, $0, $F6
	dc.b $11, $8, $8, $C, $F6
DATABKLPPLZRGGB_2: dc.b $3
	dc.b $EB, $A, $8, $F, $F8
	dc.b $F3, $3, $8, $18, $F0
	dc.b $3, $6, $8, $1C, $F8
DATABKLPPLZRGGB_3: dc.b $3
	dc.b $EB, $A, $8, $F, $F8
	dc.b $F3, $3, $8, $18, $F0
	dc.b $3, $6, $8, $1C, $F8
DATABKLPPLZRGGB_4: dc.b $3
	dc.b $EB, $A, $8, $F, $F8
	dc.b $F3, $3, $8, $18, $F0
	dc.b $3, $6, $8, $1C, $F8
DATABKLPPLZRGGB_5: dc.b $3
	dc.b $3, $A, $18, $F, $EB
	dc.b $F3, $3, $18, $18, $E3
	dc.b $EB, $6, $18, $1C, $EB
DATABKLPPLZRGGB_6: dc.b $2
	dc.b $F1, $B, $8, $0, $F6
	dc.b $11, $8, $8, $C, $F6
	even