; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 12 2020 22:04:39 GMT+0100 (GMT Summer Time)
; ================================================================================

DATAZNMNY5IBANH:
	dc.w DATAZNMNY5IBANH_0-DATAZNMNY5IBANH, DATAZNMNY5IBANH_1-DATAZNMNY5IBANH
	dc.w DATAZNMNY5IBANH_2-DATAZNMNY5IBANH, DATAZNMNY5IBANH_3-DATAZNMNY5IBANH
DATAZNMNY5IBANH_0: dc.b $2
	dc.b $F8, $D, $0, $0, $B8
	dc.b $F8, $D, $0, $8, $D8
DATAZNMNY5IBANH_1: dc.b $C
	dc.b $F8, $D, $0, $14, $5
	dc.b $F8, $D, $0, $C, $25
	dc.b $F8, $0, $0, $22, $48
	dc.b $0, $0, $0, $23, $48
	dc.b $0, $0, $0, $24, $50
	dc.b $F8, $0, $0, $25, $50
	dc.b $F8, $5, $0, $C, $56
	dc.b $F8, $5, $0, $4, $65
	dc.b $F8, $0, $0, $26, $74
	dc.b $F8, $0, $0, $27, $7C
	dc.b $0, $0, $0, $28, $74
	dc.b $0, $0, $0, $29, $7C
DATAZNMNY5IBANH_2: dc.b $2
	dc.b $F8, $9, $0, $1C, $C4
	dc.b $F8, $D, $0, $8, $DC
DATAZNMNY5IBANH_3: dc.b $2
	dc.b $F8, $D, $0, $14, $C
	dc.b $F8, $D, $0, $C, $2C
	even