; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Oct 02 2020 18:58:26 GMT+0100 (GMT Summer Time)
; ================================================================================

DATAH5IBTZCLJE7:
	dc.w DATAH5IBTZCLJE7_0-DATAH5IBTZCLJE7, DATAH5IBTZCLJE7_1-DATAH5IBTZCLJE7
	dc.w DATAH5IBTZCLJE7_2-DATAH5IBTZCLJE7, DATAH5IBTZCLJE7_3-DATAH5IBTZCLJE7
	dc.w DATAH5IBTZCLJE7_4-DATAH5IBTZCLJE7, DATAH5IBTZCLJE7_5-DATAH5IBTZCLJE7
	dc.w DATAH5IBTZCLJE7_6-DATAH5IBTZCLJE7, DATAH5IBTZCLJE7_7-DATAH5IBTZCLJE7
DATAH5IBTZCLJE7_0: dc.b $2
	dc.b $EC, $B, $0, $0, $F8
	dc.b $C, $C, $0, $C, $F0
DATAH5IBTZCLJE7_1: dc.b $3
	dc.b $FC, $D, $0, $10, $F0
	dc.b $EC, $B, $0, $0, $F8
	dc.b $C, $C, $0, $C, $F0
DATAH5IBTZCLJE7_2: dc.b $2
	dc.b $EC, $9, $0, $18, $F8
	dc.b $FC, $E, $0, $1E, $F0
DATAH5IBTZCLJE7_3: dc.b $2
	dc.b $EC, $9, $0, $2A, $F8
	dc.b $FC, $E, $0, $30, $F0
DATAH5IBTZCLJE7_4: dc.b $2
	dc.b $EC, $9, $8, $2A, $F0
	dc.b $FC, $E, $8, $30, $F0
DATAH5IBTZCLJE7_5: dc.b $3
	dc.b $EC, $6, $0, $3C, $F0
	dc.b $EC, $6, $8, $3C, $0
	dc.b $4, $D, $0, $42, $F0
DATAH5IBTZCLJE7_6: dc.b $7
	dc.b $B2, $C, $0, $4A, $F8
	dc.b $BA, $F, $0, $4E, $F0
	dc.b $BA, $5, $0, $5E, $10
	dc.b $CA, $2, $0, $62, $10
	dc.b $DA, $C, $0, $65, $F0
	dc.b $E2, $8, $0, $69, $F8
	dc.b $EA, $5, $0, $6C, $F8
DATAH5IBTZCLJE7_7: dc.b $17
	dc.b $8B, $F, $0, $70, $5
	dc.b $93, $7, $0, $80, $F5
	dc.b $9B, $B, $0, $88, $DD
	dc.b $A3, $F, $0, $94, $25
	dc.b $AB, $F, $0, $A4, $5
	dc.b $AB, $F, $0, $B4, $4D
	dc.b $B3, $7, $0, $C4, $F5
	dc.b $B3, $3, $0, $CC, $45
	dc.b $BB, $7, $0, $D0, $E5
	dc.b $C3, $F, $0, $D8, $25
	dc.b $CB, $E, $0, $E8, $5
	dc.b $CB, $2, $0, $F4, $4D
	dc.b $D3, $7, $0, $F7, $F5
	dc.b $D3, $1, $0, $FF, $45
	dc.b $DB, $3, $1, $1, $ED
	dc.b $E3, $7, $1, $5, $DD
	dc.b $E3, $3, $1, $D, $5
	dc.b $E3, $4, $1, $11, $D
	dc.b $E3, $C, $1, $13, $25
	dc.b $EB, $2, $1, $17, $D5
	dc.b $EB, $4, $1, $1A, $2D
	dc.b $F3, $1, $1, $1C, $CD
	dc.b $F3, $6, $1, $1E, $F5
	even