; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Oct 01 2020 19:11:33 GMT+0100 (GMT Summer Time)
; ================================================================================

DATA9MNMO9QQ12T:
	dc.w DATA9MNMO9QQ12T_0-DATA9MNMO9QQ12T
DATA9MNMO9QQ12T_0: dc.b $3
	dc.b $F0, $F, $0, $0, $D0
	dc.b $F0, $F, $0, $10, $F0
	dc.b $F0, $F, $0, $20, $10
	even