; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Aug 21 2020 18:11:59 GMT+0100 (GMT Summer Time)
; ================================================================================

DATAQXS8WFK1EP:
	dc.w $0, DATAQXS8WFK1EP_1-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_2-DATAQXS8WFK1EP, DATAQXS8WFK1EP_3-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_4-DATAQXS8WFK1EP, DATAQXS8WFK1EP_5-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_6-DATAQXS8WFK1EP, DATAQXS8WFK1EP_7-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_8-DATAQXS8WFK1EP, DATAQXS8WFK1EP_9-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_A-DATAQXS8WFK1EP, DATAQXS8WFK1EP_B-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_C-DATAQXS8WFK1EP, DATAQXS8WFK1EP_D-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_E-DATAQXS8WFK1EP, DATAQXS8WFK1EP_F-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_10-DATAQXS8WFK1EP, DATAQXS8WFK1EP_11-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_12-DATAQXS8WFK1EP, DATAQXS8WFK1EP_13-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_14-DATAQXS8WFK1EP, DATAQXS8WFK1EP_15-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_16-DATAQXS8WFK1EP, DATAQXS8WFK1EP_17-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_18-DATAQXS8WFK1EP, DATAQXS8WFK1EP_19-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_1A-DATAQXS8WFK1EP, DATAQXS8WFK1EP_1B-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_1C-DATAQXS8WFK1EP, DATAQXS8WFK1EP_1D-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_1E-DATAQXS8WFK1EP, DATAQXS8WFK1EP_1F-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_20-DATAQXS8WFK1EP, DATAQXS8WFK1EP_21-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_22-DATAQXS8WFK1EP, DATAQXS8WFK1EP_23-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_24-DATAQXS8WFK1EP, DATAQXS8WFK1EP_25-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_26-DATAQXS8WFK1EP, DATAQXS8WFK1EP_27-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_28-DATAQXS8WFK1EP, DATAQXS8WFK1EP_29-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_2A-DATAQXS8WFK1EP, DATAQXS8WFK1EP_2B-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_2C-DATAQXS8WFK1EP, DATAQXS8WFK1EP_2D-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_2E-DATAQXS8WFK1EP, DATAQXS8WFK1EP_2F-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_30-DATAQXS8WFK1EP, DATAQXS8WFK1EP_31-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_32-DATAQXS8WFK1EP, DATAQXS8WFK1EP_33-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_34-DATAQXS8WFK1EP, DATAQXS8WFK1EP_35-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_36-DATAQXS8WFK1EP, DATAQXS8WFK1EP_37-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_38-DATAQXS8WFK1EP, DATAQXS8WFK1EP_39-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_3A-DATAQXS8WFK1EP, DATAQXS8WFK1EP_3B-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_3C-DATAQXS8WFK1EP, DATAQXS8WFK1EP_3D-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_3E-DATAQXS8WFK1EP, DATAQXS8WFK1EP_3F-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_40-DATAQXS8WFK1EP, DATAQXS8WFK1EP_41-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_42-DATAQXS8WFK1EP, DATAQXS8WFK1EP_43-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_44-DATAQXS8WFK1EP, DATAQXS8WFK1EP_45-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_46-DATAQXS8WFK1EP, DATAQXS8WFK1EP_47-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_48-DATAQXS8WFK1EP, DATAQXS8WFK1EP_49-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_4A-DATAQXS8WFK1EP, DATAQXS8WFK1EP_4B-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_4C-DATAQXS8WFK1EP, DATAQXS8WFK1EP_4D-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_4E-DATAQXS8WFK1EP, DATAQXS8WFK1EP_4F-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_50-DATAQXS8WFK1EP, DATAQXS8WFK1EP_51-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_52-DATAQXS8WFK1EP, DATAQXS8WFK1EP_53-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_54-DATAQXS8WFK1EP, DATAQXS8WFK1EP_55-DATAQXS8WFK1EP
	dc.w DATAQXS8WFK1EP_56-DATAQXS8WFK1EP, DATAQXS8WFK1EP_57-DATAQXS8WFK1EP
	dc.w $0
DATAQXS8WFK1EP_1: dc.b $4
	dc.b $ED, $8, $0, $0, $F0
	dc.b $F5, $D, $0, $3, $F0
	dc.b $5, $8, $0, $B, $F0
	dc.b $D, $8, $0, $E, $F6
DATAQXS8WFK1EP_2: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $8, $0, $C, $F8
DATAQXS8WFK1EP_3: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $8, $0, $C, $F8
DATAQXS8WFK1EP_4: dc.b $2
	dc.b $EE, $B, $0, $0, $EF
	dc.b $E, $8, $0, $C, $F7
DATAQXS8WFK1EP_5: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAQXS8WFK1EP_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATAQXS8WFK1EP_7: dc.b $4
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
	dc.b $BB, $0, $0, $14, $AB
	dc.b $D7, $0, $0, $15, $E4
DATAQXS8WFK1EP_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATAQXS8WFK1EP_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATAQXS8WFK1EP_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATAQXS8WFK1EP_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATAQXS8WFK1EP_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATAQXS8WFK1EP_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATAQXS8WFK1EP_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATAQXS8WFK1EP_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATAQXS8WFK1EP_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATAQXS8WFK1EP_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATAQXS8WFK1EP_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATAQXS8WFK1EP_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATAQXS8WFK1EP_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATAQXS8WFK1EP_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATAQXS8WFK1EP_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAQXS8WFK1EP_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATAQXS8WFK1EP_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATAQXS8WFK1EP_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATAQXS8WFK1EP_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATAQXS8WFK1EP_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATAQXS8WFK1EP_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATAQXS8WFK1EP_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATAQXS8WFK1EP_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAQXS8WFK1EP_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAQXS8WFK1EP_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAQXS8WFK1EP_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAQXS8WFK1EP_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAQXS8WFK1EP_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAQXS8WFK1EP_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAQXS8WFK1EP_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAQXS8WFK1EP_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAQXS8WFK1EP_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAQXS8WFK1EP_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAQXS8WFK1EP_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAQXS8WFK1EP_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAQXS8WFK1EP_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAQXS8WFK1EP_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAQXS8WFK1EP_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAQXS8WFK1EP_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAQXS8WFK1EP_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAQXS8WFK1EP_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAQXS8WFK1EP_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAQXS8WFK1EP_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAQXS8WFK1EP_33: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAQXS8WFK1EP_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAQXS8WFK1EP_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAQXS8WFK1EP_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAQXS8WFK1EP_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATAQXS8WFK1EP_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATAQXS8WFK1EP_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATAQXS8WFK1EP_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATAQXS8WFK1EP_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATAQXS8WFK1EP_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAQXS8WFK1EP_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAQXS8WFK1EP_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATAQXS8WFK1EP_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAQXS8WFK1EP_40: dc.b $4
	dc.b $E8, $D, $0, $0, $F4
	dc.b $F8, $A, $0, $8, $F4
	dc.b $0, $0, $0, $11, $EC
	dc.b $10, $4, $0, $12, $F4
DATAQXS8WFK1EP_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAQXS8WFK1EP_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAQXS8WFK1EP_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAQXS8WFK1EP_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAQXS8WFK1EP_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAQXS8WFK1EP_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAQXS8WFK1EP_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAQXS8WFK1EP_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAQXS8WFK1EP_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATAQXS8WFK1EP_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATAQXS8WFK1EP_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATAQXS8WFK1EP_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAQXS8WFK1EP_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAQXS8WFK1EP_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATAQXS8WFK1EP_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATAQXS8WFK1EP_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAQXS8WFK1EP_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATAQXS8WFK1EP_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAQXS8WFK1EP_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATAQXS8WFK1EP_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATAQXS8WFK1EP_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATAQXS8WFK1EP_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATAQXS8WFK1EP_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even